"""Seed patterns that exhibit the structures found. Run: python3 seeds.py > ../results/seeds.md

Every structure lives on a zero background unless stated. Rows are passes.
'#' = 1, '.' = 0. Offsets k as stated. Leftmost cell of each diagram is
ring cell 0; the ring is long enough that nothing wraps unless said so.
"""
import sys
from ring import pass_, to_str, from_str, run
from bg import comoving


def show(title, k, seed, passes, width=None, note=""):
    s = from_str(seed)
    n = width or (len(s) + 30)
    s = s + [0] * (n - len(s))
    print("### %s  (k=%d, seed `%s`)\n" % (title, k, seed))
    if note:
        print(note + "\n")
    print("```")
    for t, r in enumerate(run(s, k, passes)):
        print("%4d %s" % (t, to_str(r)))
    print("```\n")


def show_ring(title, k, ring, passes, note="", v=0):
    s = from_str(ring)
    print("### %s  (k=%d, N=%d)\n" % (title, k, len(s)))
    if note:
        print(note + "\n")
    print("```")
    rows = run(s, k, passes)
    if v:
        rows = comoving(rows, v, len(s))
    for t, r in enumerate(rows):
        print("%4d %s" % (t, to_str(r)))
    print("```\n")


print("# Seed patterns\n")
print("Generated by `sim/seeds.py`. See REPORT.md for what each one demonstrates.\n")

print("## 1. Fixed points: any configuration with no two adjacent ones\n")
show("Isolated ones never move (all k)", 3, "#.#..#...#", 3)

print("## 2. Pinned left edge and 2-power periods in vacuum\n")
show("The `11` oscillator, period 2", 3, "##", 4,
     note="An adjacent pair fires k cells ahead every pass; the target toggles back next pass.")
show("Period 8 word", 3, "###.##", 9)
show("Period 16 word", 3, "##.###", 17)
show("Period 32 solid run", 3, "#######", 33, width=24)

print("## 3. Floods: the only long-range signal\n")
show("`1^k` followed by zeros floods (k=3)", 3, "###", 1, width=30,
     note="Window 1^k is the unique window state that survives zero input. The flood turns every zero into a one until it meets a one.")
show("A flood stops at the first one, deletes it, and complements the next cell", 3, "###......#....", 1, width=30)
show("For k=2 an adjacent pair floods immediately", 2, "##", 1, width=30)

print("## 4. Ash: what a flooded region does afterwards\n")
show("Solid run of 20 (k=3): splits into `11100` phrases, re-emits floods", 3, "####################", 16, width=34)
show("Solid run of 20 (k=2)", 2, "####################", 10, width=32)

print("## 5. Emitter + stopper = counters (odometers)\n")
show("`111 000 1`: period 8", 3, "###...#", 9, width=20,
     note="The block `111` re-emits a flood every few passes; the stopper absorbs it and is pushed one cell right; the ash between them cycles.")
show("`111 00000 1`: period 32, stopper drifts right", 3, "###.....#", 33, width=32)
show("`111 0000 1`: the stopper is destroyed, then the flood escapes", 3, "###....#", 6, width=34)
show("k=2: the pair eats every stopper to its right, one per cycle, then floods forever", 2, "##....#.....#", 42, width=44)

print("## 6. Robust traveling backgrounds (bi-infinite; shown on a ring whose length is a multiple of the period)\n")
show_ring("k=2, period 9, shift 5 per pass (co-moving frame)", 2, "..####.##" * 6, 10, v=5,
          note="Row t is rotated by 5t so a pure shift appears static. The seam (cell 0) is a defect because the pass boundary breaks translation symmetry.")
show_ring("k=3, period 10, shift 5 per pass (co-moving frame)", 3, "...##.#.##" * 6, 8, v=5)
show_ring("k=4, period 12, shift 6 per pass (co-moving frame)", 4, "....##..#.##" * 5, 8, v=6)

print("## 7. Dense random rings: no visible local structure\n")
import random
random.seed(7)
for k in (2, 3):
    s = "".join("#" if random.random() < 0.5 else "." for _ in range(64))
    show_ring("random ring, k=%d" % k, k, s, 24)
