"""Tables for raycast.asm (ordinary data memory: sine-derived, reciprocal, projection).  Run: python3 rc_data.py
writes lib/raycast_tables.inc.  The tables are also imported by the Python reference model in check_raycast.py."""
import math
NANG = 1024                    # angle units per turn
NCOL = 160                     # view width
FOV = 64.0                     # degrees
SPEED = 22                     # movement per frame in 1/256 cell
MAP = [
 "1111111111111111",
 "1000000000000001",
 "1000000000000001",
 "1002200000033001",
 "1002000000003001",
 "1000000100000001",
 "1000000100000001",
 "1000000000000001",
 "1000333000011001",
 "1000300000010001",
 "1000300000010001",
 "1000000000000001",
 "1022000000000001",
 "1020000011000001",
 "1000000000000001",
 "1111111111111111"]
START = (2 * 256 + 128, 2 * 256 + 128, 0)   # x, y (1/256 cell), angle
CEIL, FLOOR = 0x2965, 0x4A69                  # RGB565
WALL = {1: (0xD6BA, 0x9492), 2: (0xF800, 0xA000), 3: (0x07E0, 0x0540)}   # (x-side, y-side shade)
HGT_K = 1600

def tables():
    T = {}
    cs = [math.cos(2 * math.pi * a / NANG) for a in range(NANG)]
    sn = [math.sin(2 * math.pi * a / NANG) for a in range(NANG)]
    def dd(v): return 0xFFFF if abs(v) < 1e-9 else min(0xFFFF, round(256 / abs(v)))
    T["ddxl"] = [dd(c) & 255 for c in cs]; T["ddxh"] = [dd(c) >> 8 for c in cs]
    T["ddyl"] = [dd(s) & 255 for s in sn]; T["ddyh"] = [dd(s) >> 8 for s in sn]
    T["stx"] = [1 if c >= 0 else 255 for c in cs]; T["sty"] = [16 if s >= 0 else 240 for s in sn]
    T["mvx"] = [round(c * SPEED) & 255 for c in cs]; T["mvy"] = [round(s * SPEED) & 255 for s in sn]
    half = math.tan(math.radians(FOV / 2))
    offs, cosv = [], []
    for c in range(NCOL):
        u = (c + 0.5 - NCOL / 2) / (NCOL / 2) * half
        a = math.atan(u)
        offs.append(round(a / (2 * math.pi) * NANG) & 0xFFFF)
        cosv.append(min(255, round(math.cos(a) * 256)))
    T["offl"] = [o & 255 for o in offs]; T["offh"] = [o >> 8 for o in offs]; T["coso"] = cosv
    T["hgt"] = [100 if d < 16 else min(100, round(HGT_K / d)) for d in range(256)]
    T["map"] = [int(ch) for row in MAP for ch in row]
    wc = []
    for v in range(4):
        x, y = WALL.get(v, (0, 0))
        wc += [x >> 8, x & 255, y >> 8, y & 255]
    T["wcol"] = wc
    return T

LAYOUT = [("map", 0x0400), ("offl", 0x0500), ("offh", 0x0600), ("coso", 0x0700), ("hgt", 0x0800), ("wcol", 0x0900),
          ("ddxl", 0x1000), ("ddxh", 0x1400), ("ddyl", 0x1800), ("ddyh", 0x1C00),
          ("stx", 0x2000), ("sty", 0x2400), ("mvx", 0x2800), ("mvy", 0x2C00)]

def write_inc(path):
    T = tables(); out = ["; generated by rc_data.py (angles: %d per turn, %d columns, FOV %g)" % (NANG, NCOL, FOV), ".data"]
    for name, addr in LAYOUT:
        out.append(".org 0x%04X" % addr); out.append(name + ":")
        v = T[name]
        for i in range(0, len(v), 32):
            out.append("        .byte " + ",".join(str(x) for x in v[i:i + 32]))
    open(path, "w").write("\n".join(out) + "\n.code\n")

if __name__ == "__main__":
    import os
    write_inc(os.path.join(os.path.dirname(os.path.abspath(__file__)), "lib", "raycast_tables.inc"))
